# Generated by Django 5.0.7 on 2024-08-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['-deadline'], 'verbose_name': 'SubTask'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline'], 'verbose_name': 'Task'},
        ),
    ]
